package com.spectra.fieldforce.salesapp.model

data class UpdateOppurtunity(
    val Action: String,
    val Authkey: String,
    val area: String,
    val buildingNo: String,
    val buildingname: String,
    val city: String,
    val companySelf: String,
    val contactPerson: String,
    val country: String,
    val customerSegment: String,
    val emailaddress: String,
    val existingprovider: String,
    val firewall: String,
    val firewallAwc: String?,
    val firmtype: String,
    val floor: String,
    val industry: String,
    val lco: String,
    val media: String,
    val mobilephone: String,
    val oppId: String,
    val password: String?,
    val poLock: String?,
    val poNext: String?,
    val postalCode: String,
    val priceList: String,
    val redunancy: String,
    val salutation: String,
    val state: String,
    val topic: String,
    val upTimesla: String,
    val userName: String?,
    val reason:String,
    val createAreaOrBuilding: Boolean?,
    val specificArea:String,
    val specificBuilding:String,
    val noOfUsers:String?,
    val noOfBeds:String,
    val typeOfOrder:String?,
    val pocClosureDate:String?,
    val SDWANOpp:SDWANOpp?
)

data class SDWANOpp(
    val noOfLocation:String?,
    val customerILLservices:String?,
    val numberOfLinksIll:String?,
    val customerBroadbandServices:String?,
    val numberOfLinksBroadbandServices:String?,
    val linksManagedLinks:String?,
    val customerRoutingServices:String?,
    val firewallSetToExpire:String?,
    val indicationITSpent:String?,
    val currentOperationalCity:String?,
    val networkSecurityServices:String?,
    val applicationsHosted:String?,
    val itSupport:String?,
    val redundancyMPLS:String?,
    val mPLSBackbone:String?,
    val mPLSContract:String?,
    val sdwanRemarks:String?,
)

