package com.spectra.fieldforce.salesapp.model

data class UpdateOppurtunity(
    val Action: String,
    val Authkey: String,
    val area: String,
    val buildingNo: String,
    val buildingname: String,
    val city: String,
    val companySelf: String,
    val contactPerson: String,
    val country: String,
    val customerSegment: String,
    val emailaddress: String,
    val existingprovider: String,
    val firewall: String,
    val firewallAwc: String,
    val firmtype: String,
    val floor: String,
    val industry: String,
    val lco: String,
    val media: String,
    val mobilephone: String,
    val oppId: String,
    val password: String,
    val poLock: String,
    val poNext: String,
    val postalCode: String,
    val priceList: String,
    val redunancy: String,
    val salutation: String,
    val state: String,
    val topic: String,
    val upTimesla: String,
    val userName: String
)