package com.spectra.fieldforce.model

data class AddBucketListRequest(
    val AccountTurnOver: String,
    val Action: String,
    val AppointmentDate: String,
    val AreaName: String,
    val Authkey: String,
    val CRM_status: String,
    val ContactNo: String,
    val ContactPerson: String,
    val CustomerAddress: String,
    val CustomerCategory: String,
    val CustomerCityId: String,
    val CustomerID: String,
    val CustomerName: String,
    val EngineerID: String,
    val EngineerName: String,
    val ExternalCustomerSegment: String,
    val HoldCategory: String,
    val HoldReason: String,
    val IRSlaClock: String,
    val IRstatus: String,
    val ItemConsumption: String,
    val OrderCreatedOn: String,
    val Order_id: String,
    val Order_type: String,
    val Product: String,
    val Segment: String,
    val SlaStatus: String,
    val VendorCode: String,
    val VendorName: String,
    val WCRId: String,
    val WCRSlaClock: String,
    val WCRstatus: String,
    val ActivationOTP:String
)